baseURL = 'https://ephos.github.io/'
languageCode = "en"
DefaultContentLanguage = "en"
title = 'Bobby Codes'
theme = 'risotto'
copyright = "© Rob Pleau"
enableEmoji = true

#enableGitInfo = true

enableInlineShortcodes = true
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]

# Automatically add content sections to main menu
#sectionPagesMenu = "main"

[params]
noindex = false

[params.author]
Name = "Bobby"

[params.theme]
    palette = "tokyo-night-dark"
    #palette = "windows-95"

[params.about]
    title = "Bobby Codes"
    logo = "💜"
    description = "\"I dont understand, I don't know anything about it.\""

[[params.socialLinks]]
    icon = "fa-brands fa-github"
    title = "GitHub"
    url = "https://github.com/ephos"

[[params.socialLinks]]
    icon = "fa-brands fa-linkedin"
    title = "LinkedIn"
    url = "https://www.linkedin.com/in/rob-pleau/"

[[params.socialLinks]]
    icon = "fa-solid fa-user-tie"
    title = "Resume"
    url = "https://robpleau.com"

[[params.socialLinks]]
    icon = "fa-solid fa-envelope"
    title = "Email"
    url = "mailto:rj.pleau@gmail.com"

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 20

  [[menu.main]]
    identifier = "categories"
    name = "categories"
    url = "/categories/"
    weight = 30

  [[menu.main]]
    identifier = "tags"
    name = "tags"
    url = "/tags/"
    weight = 40

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[taxonomies]
category = "categories"
tag = "tags"
#series = "series"

# For hugo >= 0.60.0, enable inline HTML
[markup.goldmark.renderer]
unsafe = true

[markup]

  # Table of contents
  # Add toc = true to content front matter to enable
  [markup.tableOfContents]
    startLevel = 2
    endLevel   = 3
    ordered    = true

  [markup.highlight]
    style = 'monokai'

[services]
  [services.googleAnalytics]
    id = 'G-SSZC05V5X6'
